export const AuthorizationActionTypes = {
	AUTH_SET_ACCESS_TOKEN: "AUTH_SET_ACCESS_TOKEN",
	AUTH_SET_IS_AUTHENTICATED: "AUTH_SET_IS_AUTHENTICATED",
	AUTH_SET_ROLE: "AUTH_SET_ROLE",
};

export const UserInformationActionTypes = {
	USER_GET_ALL_INFORMATION: "USER_GET_ALL_INFORMATION",
	USER_UPDATE_INFORMATION: "USER_UPDATE_INFORMATION",
	USER_UPDATE_INFORMATION_FULFILLED: "USER_UPDATE_INFORMATION_FULFILLED",
	USER_UPDATE_INFORMATION_REJECTED: "USER_UPDATE_INFORMATION_REJECTED",
};
