export const AuthorizationActionTypes = {
	AUTH_SET_ACCESS_TOKEN: "AUTH_SET_ACCESS_TOKEN",
	AUTH_SET_REFRESH_TOKEN: "AUTH_SET_REFRESH_TOKEN",
	AUTH_SET_IS_AUTHENTICATED: "AUTH_SET_IS_AUTHENTICATED",
	AUTH_SET_ROLE: "AUTH_SET_ROLE",
};

export const UserInformationActionTypes = {
	USER_GET_ALL_INFORMATION: "USER_GET_ALL_INFORMATION",

	USER_GET_ALL_RECEIVERS: "USER_GET_ALL_RECEIVERS",
	// USER_GET_ALL_RECEIVERS_PENDING: "USER_GET_ALL_RECEIVERS_PENDING",
	USER_GET_ALL_RECEIVERS_FULFILLED: "USER_GET_ALL_RECEIVERS_FULFILLED",
	USER_GET_ALL_RECEIVERS_REJECTED: "USER_GET_ALL_RECEIVERS_REJECTED",

	USER_UPDATE_INFORMATION: "USER_UPDATE_INFORMATION",
	// USER_UPDATE_INFORMATION_PENDING: "USER_UPDATE_INFORMATION_PENDING",
	USER_UPDATE_INFORMATION_FULFILLED: "USER_UPDATE_INFORMATION_FULFILLED",
	USER_UPDATE_INFORMATION_REJECTED: "USER_UPDATE_INFORMATION_REJECTED",
};

export const UserTransactionsActionTypes = {
	USER_GET_ALL_TRANSACTIONS: "USER_GET_ALL_TRANSACTIONS",
	// USER_GET_ALL_TRANSACTIONS_PENDING: "USER_GET_ALL_TRANSACTIONS_PENDING",
	USER_GET_ALL_TRANSACTIONS_FULFILLED: "USER_GET_ALL_TRANSACTIONS_FULFILLED",
	USER_GET_ALL_TRANSACTIONS_REJECTED: "USER_GET_ALL_TRANSACTIONS_REJECTED",
};

export const UserNotificationActionTypes = {
	USER_SET_ALL_NOTIFICATION: "USER_SET_ALL_NOTIFICATION",
};
